model:
  architecture: null
  input_size: null
  output_size: null
  dropout: 0.2
  question_encoder:
    architecture: LSTMEncoder
    hidden_size: 256
    embed_size: 256
    vocab_size: null
  frame_encoder:
    architecture: CNN2Dv1
    num_channels: 16
    num_layers: 3
    input_size: 256
    kernel_size: 5
    stride: 2
    padding: 2
  mlp:
    activation: tanh
    num_layers: 1
    hidden_size: 256
    input_size: null
