model:
  architecture: LRCNBaseline
  num_answers: null
  question_encoder:
    input_size: null
    hidden_size: 256
    embed_size: 256
  convnet:
    architecture: ShallowCNN
    num_channels: 16
    num_layers: 3
    input_width: 256
    input_height: 256
    input_depth: 0
    kernel_size:
      - 1
      - 5
      - 5
    stride:
      - 1
      - 2
      - 2
  mlp:
    activation: relu
    num_layers: 1
    hidden_size: 128
    input_size: null
  video_encoder:
    hidden_size: 128
    input_size: null
