# @package _group_
architecture: LRCNBaseline
input_size: null
output_size: null
dropout: 0.0
question_encoder:
  architecture: LSTMEncoder
  input_size: null
  hidden_size: 256
  embed_size: 256
frame_encoder:
  architecture: resnet18
  input_size: 256
  pretrained: true
  freeze: false
  num_layers: 4
mlp:
  activation: tanh
  num_layers: 1
  hidden_size: 256
  input_size: null
video_encoder:
  hidden_size: 256
  input_size: null
