# hydra related
hydra:
  run:
    dir: .

# experiment
seed: 1
trainer:
  gpus: 1

# data loader
loader:
  batch_size: 32
  pin_memory: false
  num_workers: 0
  shuffle: false

# dataset
dataset:
  path: ~/data/intphys/Dataset_3000_230920

# checkpoint path
checkpoint: null

# output path
output: null

# defaults
defaults:
  - hydra/job_logging: disabled
