# hydra related
hydra:
  run:
    dir: .

# experiment
seed: 1
train: true
test: true
trainer:
  gpus: 1
  max_epochs: 30
  gradient_clip_val: 5.0
  val_check_interval: 1.00

# data loader
loader:
  batch_size: 24
  pin_memory: false
  num_workers: 0

# dataset
dataset:
  path: ~/data/intphys/Dataset_3000_230920
  fps: 3
  cached: true

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/intphys/hparams

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_accuracy"
  mode: "max"
  prefix: ""

# pretrained
pretrained: null

# model
defaults:
  - model: Baseline
  - hydra/job_logging: disabled
