# hydra related
hydra:
  run:
    dir: .

# experiment
seed: 1
train: true
test: true
trainer:
  gpus: 1
  max_epochs: 200

# data loader
loader:
  batch_size: 256
  pin_memory: false
  num_workers: 0

# dataset
dataset:
  path: ~/data/intphys/Dataset100

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/intphys

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_accuracy"
  mode: "max"
  prefix: ""

# model
defaults:
  - model: BlindBaseline
  - hydra/job_logging: disabled
