# hydra related
hydra:
  run:
    dir: .

# experiment
seed: 1
train: true
overfit: false
test: true
trainer:
  gpus: 1
  max_epochs: 30
  gradient_clip_val: 1.0
  val_check_interval: 1.00

# data loader
loader:
  batch_size: 16
  pin_memory: false
  num_workers: 0

# dataset
dataset:
  path: ~/data/intphys/Dataset_3000_230920
  fps: 1
  cached: true
  num_examples: null

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/intphys/svrhm

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_accuracy"
  mode: "max"
  prefix: ""

# pretrained
pretrained: null

# defaults
defaults:
  - model: Baseline
  - optimizer: Adam
  - scheduler: ReduceLROnPlateau
  - hydra/job_logging: disabled