# defaults
defaults:
  - model: Baseline
  - dataset: CRAFT
  - optimizer: Adam
  - scheduler: ReduceLROnPlateau
  - hydra/job_logging: disabled

# experiment
seed: 1
train: true
resume: true
overfit: false
test: true
trainer:
  gpus: 1
  max_epochs: 30
  gradient_clip_val: 1.0
  val_check_interval: 1.00
  resume_from_checkpoint: null

# data loader
loader:
  batch_size: 16
  pin_memory: false
  num_workers: 16

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/intphys/debug

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_accuracy"
  mode: "max"
  prefix: ""
  filepath: null

# resume training
checkpoint_path: null

hydra:
  run:
    dir: .
